### ISSUE TITLE
Standalone package not working

### ISSUE THREAD

**Issue by gboddin** [littlebalup/PyPS3tools#73]
```
|  _ \ _   _|  _ \/ ___|___ /  ___| |__   ___  ___| | _____ _ __
 | |_) | | | | |_) \___ \ |_ \ / __| '_ \ / _ \/ __| |/ / _ \ '__|
 |  __/| |_| |  __/ ___) |__) | (__| | | |  __/ (__|   <  __/ |
 |_|    \__, |_|   |____/____/ \___|_| |_|\___|\___|_|\_\___|_|
        |___/                                               v0.11.x

 Python checker script for PS3 flash memory dump files
 Copyright (C) 2015 littlebalup@gmail.com


Loading file "C:\Users\user\Desktop\ps3\dump.bin" to memory...
Traceback (most recent call last):
  File "checker.py", line 198, in <module>
  File "xml\etree\ElementTree.pyc", line 1182, in parse
  File "xml\etree\ElementTree.pyc", line 656, in parse
  File "xml\etree\ElementTree.pyc", line 1659, in feed
  File "xml\etree\ElementTree.pyc", line 1523, in _raiseerror
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 392, column 52


This window will be closed. Do you want to open the log file? [Y,N]?
```

**Comment by gboddin** [comment]
Fixed by replacing `Beta 1 & 2` by `Beta 1 &amp; 2` ( & is an entity etc etc ... ) 

Thank you for the tool!

**Comment by littlebalup** [comment]
Fixed https://github.com/littlebalup/PyPS3tools/commit/eaac65dea92113dd3c4b0cd5da33fd7fe4232fb0
thank you for the report
